using System.Globalization;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Data;
using NRS.Workbench.App.Services;

namespace NRS.Workbench.App.Converters;

public sealed class LocalizedTextConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is not string source || UiLanguage.Current != "en") return value ?? string.Empty;
        var match = Regex.Match(source, @"^(\d+) cambios?$", RegexOptions.CultureInvariant);
        if (match.Success) return $"{match.Groups[1].Value} changes";
        var translated = UiLanguage.Text(source);
        if (!ReferenceEquals(translated, source)) return translated;
        // These patterns are generated by RunnerProgress, not by a Git log or user path.
        translated = Regex.Replace(translated, @"\bpasos completados\b", "steps completed");
        translated = Regex.Replace(translated, @"\bpaso completado\b", "step completed");
        translated = Regex.Replace(translated, @"\bpasos\b", "steps");
        translated = Regex.Replace(translated, @"\bprocesos\b", "processes");
        translated = Regex.Replace(translated, @"\bproceso\b", "process");
        translated = Regex.Replace(translated, @"\brestante\b", "remaining");
        translated = Regex.Replace(translated, @"\bconfianza\b", "confidence");
        translated = Regex.Replace(translated, @"\bejecuciones comparables\b", "comparable runs");
        translated = Regex.Replace(translated, @"\bejecución comparable\b", "comparable run");
        translated = Regex.Replace(translated, @"^Ejecutando\b", "Running");
        translated = Regex.Replace(translated, @"^Preparando\b", "Preparing");
        return translated;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => DependencyProperty.UnsetValue;
}
