using System.Globalization;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Data;
using NRS.Workbench.App.Services;

namespace NRS.Workbench.App.Converters;

public sealed class LocalizedTextConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is not string source || UiLanguage.Current is not ("en" or "ca")) return value ?? string.Empty;
        var catalan = UiLanguage.Current == "ca";
        var match = Regex.Match(source, @"^(\d+) cambios?$", RegexOptions.CultureInvariant);
        if (match.Success) return catalan ? $"{match.Groups[1].Value} canvis" : $"{match.Groups[1].Value} changes";
        var translated = UiLanguage.Text(source);
        if (!ReferenceEquals(translated, source)) return translated;
        if (catalan)
        {
            // Only format strings produced by NRS Workbench are translated.
            // Raw runner logs, repository paths and user-authored text are not touched.
            translated = Regex.Replace(translated, @"\bpasos completados\b", "passos completats");
            translated = Regex.Replace(translated, @"\bpaso completado\b", "pas completat");
            translated = Regex.Replace(translated, @"\bpasos\b", "passos");
            translated = Regex.Replace(translated, @"\bprocesos\b", "processos");
            translated = Regex.Replace(translated, @"\bproceso\b", "procés");
            translated = Regex.Replace(translated, @"\brestante\b", "restant");
            translated = Regex.Replace(translated, @"\bconfianza\b", "confiança");
            translated = Regex.Replace(translated, @"\bejecuciones comparables\b", "execucions comparables");
            translated = Regex.Replace(translated, @"\bejecución comparable\b", "execució comparable");
            translated = Regex.Replace(translated, @"^Ejecutando\b", "Executant");
            translated = Regex.Replace(translated, @"^Preparando\b", "Preparant");
            if (translated.Contains(" jobs · ", StringComparison.Ordinal))
            {
                translated = Regex.Replace(translated, @"\bfallos\b", "errors");
                translated = Regex.Replace(translated, @"\bcancelados\b", "cancel·lats");
            }
            return translated;
        }
        // These patterns are generated by RunnerProgress, not by a Git log or user path.
        translated = Regex.Replace(translated, @"\bpasos completados\b", "steps completed");
        translated = Regex.Replace(translated, @"\bpaso completado\b", "step completed");
        translated = Regex.Replace(translated, @"\bpasos\b", "steps");
        translated = Regex.Replace(translated, @"\bprocesos\b", "processes");
        translated = Regex.Replace(translated, @"\bproceso\b", "process");
        translated = Regex.Replace(translated, @"\brestante\b", "remaining");
        translated = Regex.Replace(translated, @"\bconfianza\b", "confidence");
        translated = Regex.Replace(translated, @"\bejecuciones comparables\b", "comparable runs");
        translated = Regex.Replace(translated, @"\bejecución comparable\b", "comparable run");
        translated = Regex.Replace(translated, @"^Ejecutando\b", "Running");
        translated = Regex.Replace(translated, @"^Preparando\b", "Preparing");
        if (translated.Contains(" jobs · ", StringComparison.Ordinal))
        {
            translated = Regex.Replace(translated, @"\bfallos\b", "failures");
            translated = Regex.Replace(translated, @"\bcancelados\b", "cancelled");
        }
        return translated;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => DependencyProperty.UnsetValue;
}
